### ISSUE TITLE
Register page - new fields

### ISSUE THREAD

**Issue by rkneela** [linkcryptocoin/ChainPage#2]
- [x] Add a Drop-down  field: Field Name: Region - with Options Link Gear and Baltimore
       (add field- dropdown- Region 1) link gear 2) Baltimore)

- [x] Add one more field for Confirm password (re-confirm)

- [x] Add Username Field

- [x] -Validate  email address

- [ ]  Password (password contain digits, lowercase, upper case letters and be at least 6 characters long)

- [ ] Password Mismatch

- [ ] CSS tweaks and Validation Tweaks

**Comment by srmannem** [comment]
Resolved.

**Comment by renshan2** [comment]
Can we reopen it, since we have just got a new requirement? An additional field is needed, the field name should be TYPE, it defines the type of account is creating: Business or Person.

**Comment by srmannem** [comment]
Sure Ren, I will re-open it and start working on that.

**Comment by srmannem** [comment]
Resolved.
